---
# Disable privileged init Container creation.
sysctlInitContainer:
  enabled: false

# Restrict the use of the memory-mapping when sysctlInitContainer is disabled.
esConfig:
  elasticsearch.yml: |
    node.store.allow_mmap: false
# Permit co-located instances for solitary minikube virtual machines.
antiAffinity: "soft"

# Shrink default JVM heap.
esJavaOpts: "-Xmx512m -Xms512m"

# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "500m"
    memory: "2048M"
  limits:
    cpu: "2000m"
    memory: "4096M"

# Request smaller persistent volumes.
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: longhorn
  resources:
    requests:
      storage: 20G
