apiVersion: v1
data:
  password: UEBzc3cwcmQ=
  username: ZWxhc3RpYw==
kind: Secret
metadata:
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data: {}
      f:type: {}
    manager: kubectl-create
    operation: Update
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:password: {}
        f:username: {}
    manager: rancher
    operation: Update
  name: elastic-credentials
  namespace: default
type: Opaque
